name: AVD Deployment
 
on:
  workflow_dispatch:

permissions:
 id-token: write     
 contents: read    
jobs:
  AVDDeployment:
    name: AVD Deployment
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
         client-id: ae23c4c6-7082-464f-9a6e-7e1305db0524
         client-secret: 3ffd9a9b-a925-4164-ba51-e29d746600a9
         tenant-id: 2450d516-96a7-400d-9229-6445c4dfd62e
         subscription-id: 039e01ac-5288-42b7-b0ff-bf517c90a8e3
         
      - name: Deploy Bicep Template 
        run: |
              az deployment group create --resource-group "TR-AVD" --template-file "./quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop/main.bicep" --parameters "./quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop/params.bicepparam"
               
     # - name: Deploy
      #  uses: azure/arm-deploy@v1
       # with:
        #  subscriptionId: 7e30d173-52bf-4223-9827-cd0ea74e3e7f
         # scope: 'subscription'
         # region: centralindia
         # template: ./quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop/main.bicep
         # parameters: ./quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop/params.bicepparam 
         # failOnStdErr: false
      
        

         
